spring.application.name=virtual-threads

spring.datasource.url=jdbc:postgresql://localhost:5432/ccs-tech-db
spring.datasource.username=ccs-tech-user
spring.datasource.password=ccs-tech-password
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.show-sql = true
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=9191
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


logging.level.root=INFO
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger - %msg%n